---
id: Scheduler
name: Scheduler
full: Scheduling library
description: A scheduler system library.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Scheduler
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/core: ^3
      horde/util: ^3
      horde/vfs: ^3
